version: 2

sources:
  - name: raw_airbnb_data # Arbitrary name for the source group
    database: DB_POC       # Snowflake database
    schema: SCH_RAW        # raw schema
    tables:
      - name: RAW_HOSTS
        loaded_at_field: created_at # Considering created_at to serve as a freshness indicator
        columns:
          - name: ID
            description: "Primary key for hosts."
            tests:
              - unique
              - not_null
          - name: IS_SUPERHOST
            description: "Boolean flag indicating if the host is a superhost (t/f)."
      - name: RAW_LISTINGS
        loaded_at_field: created_at
        columns:
          - name: ID
            description: "Primary key for listings."
            tests:
              - unique
              - not_null
          - name: HOST_ID
            description: "Foreign key to the hosts table."
            tests:
              - not_null
              - relationships: # Test referential integrity
                  to: source('raw_airbnb_data', 'RAW_HOSTS')
                  field: ID
          - name: PRICE
            description: "Price of the listing, includes currency symbol."
      - name: RAW_REVIEWS
        # RAW_REVIEWS doesn't have a natural primary key in the sample
        # It also doesn't have a created_at/updated_at for loaded_at_field
        # loaded_at_field: DATE # Assuming DATE can serve this purpose
        columns:
          - name: LISTING_ID
            description: "Foreign key to the listings table."
            tests:
              - not_null
              - relationships:
                  to: source('raw_airbnb_data', 'RAW_LISTINGS')
                  field: ID
          - name: SENTIMENT
            description: "Sentiment of the review."
            tests:
              - accepted_values:
                  values: ['positive', 'negative', 'neutral']